on: [push]

jobs:
 build:
     name: sample-build
     runs-on: ubuntu-latest
     steps:
       - name: Write a multi-line message
         with: # Set the secret as an input
          super_secret: ${{ secrets.Password }}
         
