name: List S3 Buckets

on:
  push:
    branches:
      - main

jobs:
  list-s3-buckets:
    name: List S3 Buckets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS environment variables
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ATT9AepO2143cvVZ5qK3Cg8/Fltj9tUbiaIjLvEC
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 ls
