name: Workflow Dispatch Example

on:
  workflow_dispatch:

jobs:
  build:
    name: Sample Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Secret
        env:
          SUPER_SECRET: ${{ secrets.PASSWORD }}
        run: echo "Secret value is $SUPER_SECRET"
